### ISSUE TITLE
When run with multi-capabilities -  Invalid JSON file is being generated

### ISSUE THREAD

**Issue by rjayagopal** [protractor-cucumber-framework/protractor-cucumber-framework#77] opened 2017-03-21 02:08 UTC
protractor_config.js
multiCapabilities: [ {
    browserName: 'chrome',
    'chromeOptions': {
      'args': ['--show-fps-counter=true']
    }
  }, {
    browserName: 'firefox'
  }, {
    browserName: 'safari'
  }, {
    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['show-fps-counter=true'],
      'mobileEmulation': {
        'deviceName': 'Apple iPhone 4'
      }
    }
  }],

framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  cucumberOpts: {
    tags: ['@ready', '~@wip', '~@ignore'],
    format: [
      'json:cucumber_json.json',
      'pretty:cucumber_pretty.txt',
      'progress:cucumber_progress.txt',
      'rerun:cucumber_rerun.txt',
      'snippets:cucumber_snippets.txt',
      'summary:cucumber_summary.txt',
      'usage:cucumber_usage.txt',
      'usage-json:cucumber_usage-json.json'
    ],
    require: ['../../tests/step_definitions/*.js']
  },

JSON File Generated:
At the end of the file the below is getting added.
**s"
  }
]**

**Comment by rjayagopal** [comment] 2017-03-21 02:28
the issue is sporadic. Guessing it is some kind of timing or sync problem.

Appreciate your help.

**Comment by darrinholst** [comment] 2017-03-22 13:44
There are multiple test suites writing to the same file. This is a duplicate of #46. I think the most common way that people have worked around this is generating multiple files. There's an older pr out there that does that. I think getting that up to date would be a good start and then we can see about consolidating them all in to 1 file.

**Closed by darrinholst** 2017-03-22 13:44 UTC
